name: vsdat_ui
description: UI package for Val Style Dynamics Analysis Tool
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.8.0-0
  flutter: ^3.24.0

resolution: workspace

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_adaptive_scaffold: ^0.3.2
  flutter_portal: ^1.1.4
  ternary_plot:
    git: https://github.com/ShakyaCsun/ternary_plot.git
  valorant_agents:
    path: ../valorant_agents
  vector_math: ^2.1.4

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/agents/
    - assets/agents/astra/
    - assets/agents/breach/
    - assets/agents/brimstone/
    - assets/agents/chamber/
    - assets/agents/clove/
    - assets/agents/cypher/
    - assets/agents/deadlock/
    - assets/agents/fade/
    - assets/agents/gekko/
    - assets/agents/harbor/
    - assets/agents/iso/
    - assets/agents/jett/
    - assets/agents/kayo/
    - assets/agents/killjoy/
    - assets/agents/neon/
    - assets/agents/omen/
    - assets/agents/phoenix/
    - assets/agents/raze/
    - assets/agents/reyna/
    - assets/agents/sage/
    - assets/agents/skye/
    - assets/agents/sova/
    - assets/agents/tejo/
    - assets/agents/viper/
    - assets/agents/vyse/
    - assets/agents/yoru/
    - assets/roles/
  uses-material-design: true

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true
      class_name: ValAssets
