name: valorant_agents
description: A Dart package to analyze Valorant agent compositions using Style Dynamics
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.7.0-0

resolution: workspace

dependencies:
  collection: ^1.19.0
  csv: ^6.0.0
  equatable: ^2.0.7
  freezed_annotation: ^2.4.4
  intl: ^0.19.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
