name: valorant_agents
description: A Dart package to analyze Valorant agent compositions using Style Dynamics
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.9.0-0

resolution: workspace

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  equatable: ^2.0.7
  intl: ^0.20.2
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.15
