include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    public_member_api_docs: false
    # Dart automatically formats and adds/removes trailing commas since 3.7
    require_trailing_commas: false
