include: package:very_good_analysis/analysis_options.yaml

analyzer:
  plugins:
    - custom_lint

formatter:
  trailing_commas: automate

linter:
  rules:
    public_member_api_docs: false
    use_null_aware_elements: true
