targets:
  $default:
    builders:
      freezed:
        options:
          format: true
          map: false
          when: false
      go_router_builder:
        enabled: true
        generate_for:
          - lib/app_router/routes.dart
      riverpod_generator:
        enabled: true
        generate_for:
          - lib/**/*_provider.dart
          - lib/**/provider/*.dart
          - lib/app_router/app_router.dart
