name: vsdat
description: 'Valorant Style Dynamics Analysis Tool.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0-0
  flutter: '>=3.36.0-0'

workspace:
  - packages/agents_repository
  - packages/formz_inputs
  - packages/matches_repository
  - packages/valorant_agents
  - packages/vsdat_ui

dependencies:
  agents_repository:
    path: ./packages/agents_repository
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.17
  flutter_svg: ^2.2.0
  formz: ^0.8.0
  formz_inputs:
    path: ./packages/formz_inputs
  freezed_annotation: ^3.1.0
  go_router: ^16.1.0
  intl: ^0.20.2
  logging: ^1.3.0
  matches_repository:
    path: ./packages/matches_repository
  riverpod_annotation: ^3.0.0-dev.17
  ternary_plot:
    git: https://github.com/ShakyaCsun/ternary_plot.git
  two_dimensional_scrollables: ^0.3.7
  url_launcher: ^6.3.2
  valorant_agents:
    path: ./packages/valorant_agents
  vsdat_ui:
    path: ./packages/vsdat_ui

dev_dependencies:
  build_runner: ^2.6.1
  custom_lint: ^0.8.0
  flutter_gen_runner: ^5.11.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.0
  go_router_builder: ^3.2.0
  riverpod_generator: ^3.0.0-dev.17
  riverpod_lint: ^3.0.0-dev.17
  very_good_analysis: ^9.0.0

dependency_overrides:
  material_color_utilities: ^0.13.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/csv/agents/
    - assets/csv/matches/
    - assets/icons/
