name: formz_inputs
description: Formz Inputs
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.9.0-0

resolution: workspace

dependencies:
  cross_file: ^0.3.4+2
  formz: ^0.8.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
